"""Add cost to Package

Revision ID: 2c8e0644a6b7
Revises: 700ad2f4ff7e
Create Date: 2026-03-27 00:04:32.115910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c8e0644a6b7'
down_revision = '700ad2f4ff7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('payment_method', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('cargo_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.drop_column('cargo_type')
        batch_op.drop_column('payment_method')
        batch_op.drop_column('cost')

    # ### end Alembic commands ###
