"""Add Telegram integration tables

Revision ID: 43c7e5623b8b
Revises: 
Create Date: 2026-04-17 08:38:11.534151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43c7e5623b8b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.drop_index(batch_op.f('idx_clients_counterparty_ref'))
        batch_op.drop_index(batch_op.f('idx_clients_phone'))

    with op.batch_alter_table('package_schemes', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_packages_created_by'))
        batch_op.drop_index(batch_op.f('idx_packages_draft_status'))
        batch_op.drop_column('created_in_app')
        batch_op.drop_column('created_by')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_users_telegram_user_id', ['telegram_user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_users_telegram_user_id', type_='unique')

    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('created_in_app', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True))
        batch_op.create_index(batch_op.f('idx_packages_draft_status'), ['draft_status'], unique=False)
        batch_op.create_index(batch_op.f('idx_packages_created_by'), ['created_by'], unique=False)

    with op.batch_alter_table('package_schemes', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_clients_phone'), ['phone'], unique=False)
        batch_op.create_index(batch_op.f('idx_clients_counterparty_ref'), ['counterparty_ref'], unique=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    # ### end Alembic commands ###
