"""Add seats_data JSON column

Revision ID: a08dbc11dc64
Revises: 2c8e0644a6b7
Create Date: 2026-03-28 10:21:36.581931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a08dbc11dc64'
down_revision = '2c8e0644a6b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seats_data', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.drop_column('seats_data')

    # ### end Alembic commands ###
